server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ha
spring.datasource.username=ha
spring.datasource.password=ha_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info


